import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import '@/style/globals.css';
import { Nav, Profile } from '@/component';
import { ThemeProvider } from '@/feature/context/ThemeContext';
import { NextIntlClientProvider, hasLocale } from 'next-intl';
import { notFound } from 'next/navigation';
import { routing } from '@/i18n/routing';
import ConfigBox from '@/component/ConfigBox';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: '우영경 | Younggyung ',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html lang={locale} className="dark">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <NextIntlClientProvider>
          <ThemeProvider>
            {/* 전역 헤더 */}
            <header className="sticky top-0 z-20 border-b border-gray-200 bg-green-200/70 backdrop-blur supports-[backdrop-filter]:bg-white/50 dark:border-gray-800 dark:bg-gray-950/60">
              <div className="mx-auto flex h-12 items-center justify-between px-4">
                YOKI — Front-End
                <Nav type="header" />
                <ConfigBox />
              </div>
            </header>
            {/* 본문영역 */}
            <div className="lg:flex">
              <Profile className="top-12 lg:sticky lg:h-[calc(100svh-3rem)] lg:w-[20%]" />
              <main className="mt-8 lg:w-[70%]">
                {children}
                <Nav type="mobile" />
              </main>
            </div>
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
