import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import '@/style/globals.css';
import { Profile } from '@/component';
import { ThemeProvider } from '@/feature/context/ThemeContext';
import { NextIntlClientProvider, hasLocale } from 'next-intl';
import { notFound } from 'next/navigation';
import { routing } from '@/i18n/routing';
import ConfigBox from '@/component/ConfigBox';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: '우영경 | Younggyung ',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html lang={locale} className="dark">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <NextIntlClientProvider>
          <ThemeProvider>
            {/* 전역 헤더 */}
            <header className="sticky top-0 z-50">
              <div className="mx-5 flex items-center justify-end py-1">
                <ConfigBox />
              </div>
            </header>
            {/* 본문영역 */}
            <div className="mx-10 lg:flex">
              <Profile className="lg:sticky lg:top-10 lg:max-h-[calc(100vh-2.5rem)] lg:w-[30%]" />
              <main className="mt-8 lg:w-[70%]">{children}</main>
            </div>
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
